window.NGT_MEMBERS_SEED = [
  {
    "id": "seed-001",
    "serialId": "NGT-001",
    "fullName": "Dasho Sangay Thinley",
    "serviceYear": "",
    "nyikemYear": "1995",
    "resignationYear": "",
    "joinedYear": "2010",
    "cidNo": "11410000128",
    "dateOfBirth": "01/06/47",
    "address": "Above DeSuung Training Centre, Taba, Thimphu",
    "phone": "17600942",
    "email": "",
    "lastPost": "1. Secretary, Ministry of Agriculture\n2. DG, Forests",
    "spouseOrKin": "Mrs. Kunga Choden 77109389",
    "knowledge": ""
  },
  {
    "id": "seed-002",
    "serialId": "NGT-002",
    "fullName": "Dasho Kunzang Wangdi",
    "serviceYear": "",
    "nyikemYear": "2001",
    "resignationYear": "2015",
    "joinedYear": "2016",
    "cidNo": "11410008663",
    "dateOfBirth": "17/07/53",
    "address": "Cho Sid Public Policy Publications & Studies (CSPPPS), P.O. Box 878, Rabjung Lam, Motithang, Thimphu",
    "phone": "17602000",
    "email": "dashokunzang@gmail.com",
    "lastPost": "1. Auditor General, RAA\n2. Chief Election Comissioner",
    "spouseOrKin": "Mrs. Pem Tandi 17747451",
    "knowledge": "Good governance and Election and Democracy"
  },
  {
    "id": "seed-003",
    "serialId": "NGT-003",
    "fullName": "Dasho Pem L. Dorji",
    "serviceYear": "",
    "nyikemYear": "",
    "resignationYear": "",
    "joinedYear": "2024",
    "cidNo": "10503001520",
    "dateOfBirth": "",
    "address": "Changzamto, Thimphu",
    "phone": "77490099",
    "email": "pemaldorji@gmail.com",
    "lastPost": "1. Secretary, Ministry of Labour & Human Resources",
    "spouseOrKin": "",
    "knowledge": ""
  },
  {
    "id": "seed-004",
    "serialId": "NGT-004",
    "fullName": "Dasho Dr. Gado Tshering",
    "serviceYear": "",
    "nyikemYear": "2006",
    "resignationYear": "",
    "joinedYear": "2014",
    "cidNo": "10501001024",
    "dateOfBirth": "08/05/59",
    "address": "House No. 1, Yangchenphug Colony, Thimphu",
    "phone": "17110142",
    "email": "gadotshering7@gmail.com",
    "lastPost": "1.Secretary, Ministry of Health",
    "spouseOrKin": "Thinley Jamtsho Tshering 77777007",
    "knowledge": ""
  },
  {
    "id": "seed-005",
    "serialId": "NGT-005",
    "fullName": "Dasho Rinzin Gyaltshen",
    "serviceYear": "",
    "nyikemYear": "1986",
    "resignationYear": "",
    "joinedYear": "2024",
    "cidNo": "11007000606",
    "dateOfBirth": "15/1/51",
    "address": "The Pema Hotel, Motithang, Thimphu",
    "phone": "17628118",
    "email": "rinzipem2025@gmail.com",
    "lastPost": "1. Zhung Kalyon\n2. Eminent Supreme Court Justice",
    "spouseOrKin": "Pema Gyaltshen 17602076",
    "knowledge": ""
  },
  {
    "id": "seed-006",
    "serialId": "NGT-006",
    "fullName": "Lyonpo Leki Dorji",
    "serviceYear": "",
    "nyikemYear": "1981",
    "resignationYear": "",
    "joinedYear": "2024",
    "cidNo": "11410005834",
    "dateOfBirth": "31/12/44",
    "address": "Hejo, Thimphu",
    "phone": "77123001",
    "email": "lekidoji@yahoo.com",
    "lastPost": "1. Minister of Information & Communications",
    "spouseOrKin": "Ms. Yangchen Ongmo 77604300",
    "knowledge": ""
  },
  {
    "id": "seed-007",
    "serialId": "NGT-007",
    "fullName": "Lyonpo Om Pradhan",
    "serviceYear": "",
    "nyikemYear": "1977",
    "resignationYear": "",
    "joinedYear": "2016",
    "cidNo": "11410002078",
    "dateOfBirth": "",
    "address": "Semtokha, Thimphu",
    "phone": "77605740",
    "email": "semtokha@gmail.com",
    "lastPost": "1. Permanent Representative to the U.N., New York\n2. Tengye Lyonpo",
    "spouseOrKin": "Wangyal Rigzen, Thimphu",
    "knowledge": "History, National & Regional developments, Bhutanese language"
  },
  {
    "id": "seed-008",
    "serialId": "NGT-008",
    "fullName": "Dasho Sonam Tshering",
    "serviceYear": "",
    "nyikemYear": "2006",
    "resignationYear": "",
    "joinedYear": "2018",
    "cidNo": "10805002149",
    "dateOfBirth": "03/09/58",
    "address": "27 Kunzang Lam, Lower Motithang, Thimphu",
    "phone": "17117760",
    "email": "sonamtshering39@gmail.com",
    "lastPost": "1.Secretary. Ministry of Economic Affairs \nRetired: 30 June 2016",
    "spouseOrKin": "Sangay Zam, 17603123",
    "knowledge": ""
  },
  {
    "id": "seed-009",
    "serialId": "NGT-009",
    "fullName": "Dasho Sangay Khandu",
    "serviceYear": "",
    "nyikemYear": "2009",
    "resignationYear": "",
    "joinedYear": "2024",
    "cidNo": "10811000436",
    "dateOfBirth": "27/9/56",
    "address": "Lower Motithang, Norden Lam, House No. 14, Thimphu",
    "phone": "17115454",
    "email": "dashosangaykhandu@gmail.com",
    "lastPost": "1. Chairman, DHI\n2. Secretary, National Land Commission",
    "spouseOrKin": "Dechen Om 17110897",
    "knowledge": ""
  },
  {
    "id": "seed-010",
    "serialId": "NGT-010",
    "fullName": "Dasho Dawa Tshering",
    "serviceYear": "",
    "nyikemYear": "1999",
    "resignationYear": "",
    "joinedYear": "2010",
    "cidNo": "10806000991",
    "dateOfBirth": "15/10/54",
    "address": "Paro Nemjo, Dobu, Paro",
    "phone": "17603997",
    "email": "dawatshering8@gmail.com",
    "lastPost": "1. Dzongda, Punakha\n2. DG, Bhutan Forests\nRetired: 2008",
    "spouseOrKin": "Tshering Pem 17603998",
    "knowledge": ""
  },
  {
    "id": "seed-011",
    "serialId": "NGT-011",
    "fullName": "Dasho Penjor Dorji",
    "serviceYear": "",
    "nyikemYear": "1991",
    "resignationYear": "",
    "joinedYear": "2010",
    "cidNo": "10501000165",
    "dateOfBirth": "",
    "address": "P.O. Box 916, Thimphu",
    "phone": "77117711",
    "email": "pejordorji48@gmail.com",
    "lastPost": "",
    "spouseOrKin": "",
    "knowledge": ""
  },
  {
    "id": "seed-012",
    "serialId": "NGT-012",
    "fullName": "Dasho Yeshi Wangdi",
    "serviceYear": "",
    "nyikemYear": "2012",
    "resignationYear": "",
    "joinedYear": "2020",
    "cidNo": "10710000560",
    "dateOfBirth": "03/10/59",
    "address": "10 Bangdu Lam, Chang Bangdu, Thimphu",
    "phone": "17640974",
    "email": "ywangdue@gmail.com",
    "lastPost": "Secretary, Ministry of Economic Affairs",
    "spouseOrKin": "Spouse: Lemo, 17610618; Son: Sonam Dendup, 77325961",
    "knowledge": ""
  },
  {
    "id": "seed-013",
    "serialId": "NGT-013",
    "fullName": "Dasho Ugen Chewang",
    "serviceYear": "",
    "nyikemYear": "2011",
    "resignationYear": "",
    "joinedYear": "2025",
    "cidNo": "11107001106",
    "dateOfBirth": "",
    "address": "Taba, Thimphu",
    "phone": "17603693",
    "email": "ugenchewang1955@gmail.com",
    "lastPost": "1. Auditor General, RAA\n2. Chairman, DHI",
    "spouseOrKin": "Ninda Wangmo, 17990052\nLaigden Dzed, 17350103",
    "knowledge": ""
  },
  {
    "id": "seed-014",
    "serialId": "NGT-014",
    "fullName": "Dasho Sherub Gyeltshen",
    "serviceYear": "",
    "nyikemYear": "1997",
    "resignationYear": "",
    "joinedYear": "2025",
    "cidNo": "11410003114",
    "dateOfBirth": "16/12/54",
    "address": "House No. 32, Motithang, Thimphu",
    "phone": "17609577",
    "email": "shegyel9@gmail.com",
    "lastPost": "1. Minister, Ministry of Home Affairs \n2. Secretary, Dzongkha Development Commission",
    "spouseOrKin": "Sonam Yangtsho, 17110690",
    "knowledge": ""
  },
  {
    "id": "seed-015",
    "serialId": "NGT-015",
    "fullName": "Dasho Phuntso Norbu",
    "serviceYear": "",
    "nyikemYear": "2012",
    "resignationYear": "2018",
    "joinedYear": "2020",
    "cidNo": "10710001921",
    "dateOfBirth": "01/01/59",
    "address": "House No. 1, Changjalu, Thimphu",
    "phone": "17112103",
    "email": "phuntsonorbu9@gmail.com",
    "lastPost": "1. DG Dept. of Industry, Ministry of Economic Affairs\n2. JMD Punatshangchu- I & II HEPs.",
    "spouseOrKin": "Sangay Choden, 17629914\nTsering Dema, 17884480",
    "knowledge": "Applied geology, hydropower construction & industrial development"
  },
  {
    "id": "seed-016",
    "serialId": "NGT-016",
    "fullName": "Dasho Sherub Tenzin",
    "serviceYear": "",
    "nyikemYear": "",
    "resignationYear": "",
    "joinedYear": "2012",
    "cidNo": "10715000153",
    "dateOfBirth": "06/06/51",
    "address": "Tashi Woed Seling Khim, Doled Zur Lam -172 SE, Semtokha, Thimphu",
    "phone": "77172917",
    "email": "dashosherub@yahoo.com",
    "lastPost": "1. Cabinet Secretary\n2. Ambassador to Kuwait",
    "spouseOrKin": "",
    "knowledge": ""
  },
  {
    "id": "seed-017",
    "serialId": "NGT-017",
    "fullName": "Dasho Chagyel",
    "serviceYear": "",
    "nyikemYear": "1983",
    "resignationYear": "",
    "joinedYear": "2010",
    "cidNo": "",
    "dateOfBirth": "1940",
    "address": "Upper Motithang (below Sershang School), Thimphu",
    "phone": "17600797",
    "email": "dashochagyel@gmail.com",
    "lastPost": "1. Thrimpon, High Court\n2. Thrimpon, Zhemgang/Chhukha",
    "spouseOrKin": "",
    "knowledge": ""
  },
  {
    "id": "seed-018",
    "serialId": "NGT-018",
    "fullName": "Dasho Dorjee Namgyel",
    "serviceYear": "",
    "nyikemYear": "1987",
    "resignationYear": "",
    "joinedYear": "2010",
    "cidNo": "",
    "dateOfBirth": "1949",
    "address": "Khasadrapchu, Thimphu",
    "phone": "17646593",
    "email": "",
    "lastPost": "1. MD, State Trading Corporation of Bhutan Ltd.\nRetired: 2006",
    "spouseOrKin": "",
    "knowledge": ""
  },
  {
    "id": "seed-019",
    "serialId": "NGT-019",
    "fullName": "Dasho Pem Tshering",
    "serviceYear": "",
    "nyikemYear": "",
    "resignationYear": "",
    "joinedYear": "2010",
    "cidNo": "",
    "dateOfBirth": "1943",
    "address": "",
    "phone": "",
    "email": "",
    "lastPost": "1. Judge at High Court\n2. Vice-President, BCCI",
    "spouseOrKin": "",
    "knowledge": ""
  },
  {
    "id": "seed-020",
    "serialId": "NGT-020",
    "fullName": "Dasho Zangley Dukpa",
    "serviceYear": "",
    "nyikemYear": "",
    "resignationYear": "",
    "joinedYear": "2020",
    "cidNo": "10903000774",
    "dateOfBirth": "02/02/50",
    "address": "Lubding, Thimphu",
    "phone": "17111880",
    "email": "dashozangleyd@gmail.com",
    "lastPost": "1. Minister for Health\n2. Vice-Chancellor of RUB",
    "spouseOrKin": "Mrs. Karma 17600654\nPema Namgay 77200597",
    "knowledge": "Positive Thinking and Leadership"
  },
  {
    "id": "seed-021",
    "serialId": "NGT-021",
    "fullName": "Dasho Pema Thinley",
    "serviceYear": "",
    "nyikemYear": "2006",
    "resignationYear": "",
    "joinedYear": "2016",
    "cidNo": "10709002563",
    "dateOfBirth": "17/01/51",
    "address": "Building 25, Flat 402, Dham Dhajo, Lower Motithang, Thimphu",
    "phone": "17601910",
    "email": "pemathinley326@gmail.com",
    "lastPost": "1. Secretary, Ministry of Education\n2. Vice Chancellor, RUB",
    "spouseOrKin": "1. Tshering Pelmo 17627239\n2. Palmo Thinley 17533508",
    "knowledge": "Education,"
  },
  {
    "id": "seed-022",
    "serialId": "NGT-022",
    "fullName": "Dasho Dhondup Phuntsho",
    "serviceYear": "",
    "nyikemYear": "",
    "resignationYear": "",
    "joinedYear": "2010",
    "cidNo": "11410002991",
    "dateOfBirth": "",
    "address": "",
    "phone": "77210387",
    "email": "",
    "lastPost": "",
    "spouseOrKin": "",
    "knowledge": ""
  },
  {
    "id": "seed-023",
    "serialId": "NGT-023",
    "fullName": "Dasho Sangay Tenzin",
    "serviceYear": "",
    "nyikemYear": "",
    "resignationYear": "",
    "joinedYear": "2010",
    "cidNo": "",
    "dateOfBirth": "",
    "address": "",
    "phone": "17959688",
    "email": "",
    "lastPost": "",
    "spouseOrKin": "",
    "knowledge": ""
  },
  {
    "id": "seed-024",
    "serialId": "NGT-024",
    "fullName": "Dasho Yanki T. Wangchuk",
    "serviceYear": "",
    "nyikemYear": "",
    "resignationYear": "",
    "joinedYear": "2013",
    "cidNo": "10802000597",
    "dateOfBirth": "",
    "address": "Above Memorial Chorten, Thimphu",
    "phone": "17344368",
    "email": "yankiwangchuk7@gmail.com",
    "lastPost": "1. Secretary, Ministry of Finance\n2. Auditor General, RAA",
    "spouseOrKin": "",
    "knowledge": ""
  },
  {
    "id": "seed-025",
    "serialId": "NGT-025",
    "fullName": "Dasho Pasang Tobgay",
    "serviceYear": "",
    "nyikemYear": "",
    "resignationYear": "",
    "joinedYear": "2010",
    "cidNo": "",
    "dateOfBirth": "",
    "address": "",
    "phone": "",
    "email": "",
    "lastPost": "",
    "spouseOrKin": "",
    "knowledge": ""
  },
  {
    "id": "seed-026",
    "serialId": "NGT-026",
    "fullName": "Dasho Phub Dorji",
    "serviceYear": "",
    "nyikemYear": "",
    "resignationYear": "",
    "joinedYear": "2010",
    "cidNo": "",
    "dateOfBirth": "",
    "address": "",
    "phone": "",
    "email": "",
    "lastPost": "",
    "spouseOrKin": "",
    "knowledge": ""
  },
  {
    "id": "seed-027",
    "serialId": "NGT-027",
    "fullName": "Dasho Dorji Norbu",
    "serviceYear": "",
    "nyikemYear": "",
    "resignationYear": "",
    "joinedYear": "2010",
    "cidNo": "",
    "dateOfBirth": "",
    "address": "",
    "phone": "",
    "email": "",
    "lastPost": "",
    "spouseOrKin": "",
    "knowledge": ""
  },
  {
    "id": "seed-028",
    "serialId": "NGT-028",
    "fullName": "Dasho Karma Dorjee (MTI)",
    "serviceYear": "",
    "nyikemYear": "",
    "resignationYear": "",
    "joinedYear": "2010",
    "cidNo": "11410003682",
    "dateOfBirth": "",
    "address": "Below Thimphu Deluxe Hotel, \nMotithang, Thimphu",
    "phone": "17601899",
    "email": "",
    "lastPost": "1. Secretary, Ministry of Trade, \n    Industry & Power",
    "spouseOrKin": "",
    "knowledge": ""
  },
  {
    "id": "seed-029",
    "serialId": "NGT-029",
    "fullName": "Dasho Karma Dorji (DNP)",
    "serviceYear": "",
    "nyikemYear": "",
    "resignationYear": "",
    "joinedYear": "2010",
    "cidNo": "",
    "dateOfBirth": "",
    "address": "",
    "phone": "17117666\n17720802",
    "email": "",
    "lastPost": "1. DG, Dept. of \n    National Property\n2.",
    "spouseOrKin": "",
    "knowledge": ""
  },
  {
    "id": "seed-030",
    "serialId": "NGT-030",
    "fullName": "Dasho Namgay",
    "serviceYear": "",
    "nyikemYear": "",
    "resignationYear": "",
    "joinedYear": "2010",
    "cidNo": "11910001663",
    "dateOfBirth": "",
    "address": "",
    "phone": "",
    "email": "",
    "lastPost": "",
    "spouseOrKin": "",
    "knowledge": ""
  },
  {
    "id": "seed-031",
    "serialId": "NGT-031",
    "fullName": "Dasho Phub Tshering",
    "serviceYear": "",
    "nyikemYear": "",
    "resignationYear": "",
    "joinedYear": "2010",
    "cidNo": "",
    "dateOfBirth": "",
    "address": "",
    "phone": "17600027",
    "email": "",
    "lastPost": "",
    "spouseOrKin": "",
    "knowledge": ""
  },
  {
    "id": "seed-032",
    "serialId": "NGT-032",
    "fullName": "Dasho Dr. P.W. Samdrup",
    "serviceYear": "",
    "nyikemYear": "",
    "resignationYear": "",
    "joinedYear": "2010",
    "cidNo": "",
    "dateOfBirth": "",
    "address": "",
    "phone": "17119837",
    "email": "",
    "lastPost": "",
    "spouseOrKin": "",
    "knowledge": ""
  },
  {
    "id": "seed-033",
    "serialId": "NGT-033",
    "fullName": "Dasho Dago Tshering",
    "serviceYear": "",
    "nyikemYear": "",
    "resignationYear": "",
    "joinedYear": "2010",
    "cidNo": "",
    "dateOfBirth": "",
    "address": "",
    "phone": "17603318",
    "email": "",
    "lastPost": "",
    "spouseOrKin": "",
    "knowledge": ""
  },
  {
    "id": "seed-034",
    "serialId": "NGT-034",
    "fullName": "Dasho Gasey Lhundup",
    "serviceYear": "",
    "nyikemYear": "",
    "resignationYear": "",
    "joinedYear": "2010",
    "cidNo": "",
    "dateOfBirth": "",
    "address": "",
    "phone": "",
    "email": "",
    "lastPost": "",
    "spouseOrKin": "",
    "knowledge": ""
  },
  {
    "id": "seed-035",
    "serialId": "NGT-035",
    "fullName": "Dasho Dophu Tshering",
    "serviceYear": "",
    "nyikemYear": "",
    "resignationYear": "",
    "joinedYear": "2010",
    "cidNo": "",
    "dateOfBirth": "",
    "address": "",
    "phone": "",
    "email": "",
    "lastPost": "",
    "spouseOrKin": "",
    "knowledge": ""
  },
  {
    "id": "seed-036",
    "serialId": "NGT-036",
    "fullName": "Dasho Penden Wangchuk",
    "serviceYear": "",
    "nyikemYear": "",
    "resignationYear": "",
    "joinedYear": "2016",
    "cidNo": "",
    "dateOfBirth": "",
    "address": "",
    "phone": "",
    "email": "",
    "lastPost": "",
    "spouseOrKin": "",
    "knowledge": ""
  },
  {
    "id": "seed-037",
    "serialId": "NGT-037",
    "fullName": "Dasho Lhakpa Dorji",
    "serviceYear": "",
    "nyikemYear": "",
    "resignationYear": "",
    "joinedYear": "2014",
    "cidNo": "",
    "dateOfBirth": "",
    "address": "",
    "phone": "",
    "email": "",
    "lastPost": "",
    "spouseOrKin": "",
    "knowledge": ""
  },
  {
    "id": "seed-038",
    "serialId": "NGT-038",
    "fullName": "Dasho Lhadarla",
    "serviceYear": "",
    "nyikemYear": "",
    "resignationYear": "",
    "joinedYear": "2010",
    "cidNo": "",
    "dateOfBirth": "",
    "address": "",
    "phone": "",
    "email": "",
    "lastPost": "",
    "spouseOrKin": "",
    "knowledge": ""
  },
  {
    "id": "seed-039",
    "serialId": "NGT-039",
    "fullName": "Dasho Dorji Wangdi",
    "serviceYear": "",
    "nyikemYear": "",
    "resignationYear": "",
    "joinedYear": "2010",
    "cidNo": "",
    "dateOfBirth": "",
    "address": "",
    "phone": "",
    "email": "",
    "lastPost": "",
    "spouseOrKin": "",
    "knowledge": ""
  },
  {
    "id": "seed-040",
    "serialId": "NGT-040",
    "fullName": "Dasho D.N. Katwal",
    "serviceYear": "",
    "nyikemYear": "",
    "resignationYear": "",
    "joinedYear": "2010",
    "cidNo": "",
    "dateOfBirth": "",
    "address": "",
    "phone": "",
    "email": "",
    "lastPost": "",
    "spouseOrKin": "",
    "knowledge": ""
  },
  {
    "id": "seed-041",
    "serialId": "NGT-041",
    "fullName": "Dasho Phub Dorji\n(Wachep)",
    "serviceYear": "",
    "nyikemYear": "",
    "resignationYear": "",
    "joinedYear": "2010",
    "cidNo": "",
    "dateOfBirth": "",
    "address": "",
    "phone": "",
    "email": "",
    "lastPost": "",
    "spouseOrKin": "",
    "knowledge": ""
  },
  {
    "id": "seed-042",
    "serialId": "NGT-042",
    "fullName": "Dasho H.K Humagai",
    "serviceYear": "",
    "nyikemYear": "",
    "resignationYear": "",
    "joinedYear": "2010",
    "cidNo": "",
    "dateOfBirth": "",
    "address": "",
    "phone": "",
    "email": "",
    "lastPost": "",
    "spouseOrKin": "",
    "knowledge": ""
  },
  {
    "id": "seed-043",
    "serialId": "NGT-043",
    "fullName": "Dasho Wangdi",
    "serviceYear": "",
    "nyikemYear": "",
    "resignationYear": "",
    "joinedYear": "2010",
    "cidNo": "",
    "dateOfBirth": "",
    "address": "",
    "phone": "",
    "email": "",
    "lastPost": "",
    "spouseOrKin": "",
    "knowledge": ""
  },
  {
    "id": "seed-044",
    "serialId": "NGT-044",
    "fullName": "Dasho Oko Tshering",
    "serviceYear": "",
    "nyikemYear": "",
    "resignationYear": "",
    "joinedYear": "2010",
    "cidNo": "",
    "dateOfBirth": "",
    "address": "",
    "phone": "",
    "email": "",
    "lastPost": "",
    "spouseOrKin": "",
    "knowledge": ""
  },
  {
    "id": "seed-045",
    "serialId": "NGT-045",
    "fullName": "Dasho Sangay Dorji\n(HC)",
    "serviceYear": "",
    "nyikemYear": "",
    "resignationYear": "",
    "joinedYear": "2010",
    "cidNo": "",
    "dateOfBirth": "",
    "address": "",
    "phone": "",
    "email": "",
    "lastPost": "",
    "spouseOrKin": "",
    "knowledge": ""
  },
  {
    "id": "seed-046",
    "serialId": "NGT-046",
    "fullName": "Dasho Tashi Phuntsog",
    "serviceYear": "",
    "nyikemYear": "1995",
    "resignationYear": "2012",
    "joinedYear": "2016",
    "cidNo": "1704001024",
    "dateOfBirth": "23/10/1955",
    "address": "Above Thori Resort, Lubding,\nLungtenphu, Thimphu",
    "phone": "77187777\n17777369",
    "email": "gyalrigtshang@gmail.com",
    "lastPost": "1. Cabinet Secretary\n2. Ambassador to Kuwait",
    "spouseOrKin": "Rinzin Wangmo 77228070\nKezang Choden 77246118",
    "knowledge": ""
  },
  {
    "id": "seed-047",
    "serialId": "NGT-047",
    "fullName": "Dasho Khandu",
    "serviceYear": "",
    "nyikemYear": "",
    "resignationYear": "",
    "joinedYear": "2012",
    "cidNo": "",
    "dateOfBirth": "",
    "address": "",
    "phone": "",
    "email": "",
    "lastPost": "",
    "spouseOrKin": "",
    "knowledge": ""
  },
  {
    "id": "seed-048",
    "serialId": "NGT-048",
    "fullName": "Dasho Sherab Thaye",
    "serviceYear": "",
    "nyikemYear": "",
    "resignationYear": "",
    "joinedYear": "2010",
    "cidNo": "",
    "dateOfBirth": "",
    "address": "",
    "phone": "",
    "email": "",
    "lastPost": "",
    "spouseOrKin": "",
    "knowledge": ""
  },
  {
    "id": "seed-049",
    "serialId": "NGT-049",
    "fullName": "Dasho Jambay",
    "serviceYear": "",
    "nyikemYear": "",
    "resignationYear": "",
    "joinedYear": "2010",
    "cidNo": "",
    "dateOfBirth": "",
    "address": "",
    "phone": "",
    "email": "",
    "lastPost": "",
    "spouseOrKin": "",
    "knowledge": ""
  },
  {
    "id": "seed-050",
    "serialId": "NGT-050",
    "fullName": "Dasho R.N. Dhital",
    "serviceYear": "",
    "nyikemYear": "",
    "resignationYear": "",
    "joinedYear": "2010",
    "cidNo": "",
    "dateOfBirth": "",
    "address": "",
    "phone": "",
    "email": "",
    "lastPost": "",
    "spouseOrKin": "",
    "knowledge": ""
  },
  {
    "id": "seed-051",
    "serialId": "NGT-051",
    "fullName": "Dasho Jigme Tshultim",
    "serviceYear": "",
    "nyikemYear": "",
    "resignationYear": "",
    "joinedYear": "2025",
    "cidNo": "",
    "dateOfBirth": "",
    "address": "",
    "phone": "",
    "email": "",
    "lastPost": "",
    "spouseOrKin": "",
    "knowledge": ""
  }
];
